name: continuous-integration

on:
  push:
    branches:
    - master
    - ci
    tags:
      - "*"
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Demo App
        uses: php-actions/composer@v6
        with:
          command: composer create-project symfony/symfony-demo:1.8.0 . --no-install
      - name: build
        run: docker-compose up -d