name: continuous-integration

on:
  push:
    branches:
    - master
    - ci
    tags:
      - "*"
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Demo App
        uses: php-actions/composer@v6
        with:
          command: create-project symfony/symfony-demo:1.8.0 ../demo
      - name: Copy Demo Project Source
        run: mv -f ../demo .
      - name: Build
        run: docker-compose up -d