name: continuous-integration

on:
  push:
    branches:
    - master
    - ci
    tags:
      - "*"
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: docker-compose up -d